# **4101553 Métodos Numéricos aplicados a la Ingenieria Civil**
Departamento de Ingeniería Civil\
Universidad Nacional de Colombia\
Sede Manizales

**Docente:** Juan Nicolás Ramírez Giraldo ([jnramirezg@unal.edu.co](mailto:jnramirezg@unal.edu.co))

"*Cum cogitaveris quot te antecedant, respice quot sequantur*" (**Séneca**)


[Repositorio de la asignatura](https://github.com/jnramirezg/metodos_numericos_ingenieria_civil/)




# **Unidad 1: Sistemas de ecuaciones lineales**


## **Lo más básico de Python**

In [1]:
# Los comentarios se ponen con el símbolo numeral.
''' También se pueden poner entre tres comillas sin afectar el código'''


' También se pueden poner entre tres comillas sin afectar el código'

In [2]:
4+3  # Suma


7

In [3]:
94-100  # Resta


-6

In [4]:
6*4  # Multiplicación


24

In [5]:
7/8  # División


0.875

In [6]:
9//4  # División entera


2

In [7]:
9%4  # Residuo de la división


1

In [8]:
2**10  # Potencia, que en Matlab sería 2^10


1024

In [9]:
a = -10  # Asignación de variables


In [10]:
print(a)  # Impresión dentro del código.


-10


In [11]:
a  # Impresión en consola.


-10

In [12]:
a == -10  # Condición de igualdad.


True

In [13]:
a != -10  # Condición de desigualdad.


False

In [14]:
a == -10 or a != -10  # Operador lógico 'o'.


True

In [15]:
a == -10 and a != -10  # Operador lógico 'y'


False

In [16]:
# Condicional básico
if a == 100:
    print('Correcto')
else:
    print('Incorrecto')
        

Incorrecto


In [17]:
# Ciclo for
for i in range(5):
    print(i)


0
1
2
3
4


In [18]:
# Ciclo while
contador = 0
while contador < 5:
    print(contador)
    contador += 1  # Que es equivalente a (contador = contador + 1), 
                   # es decir, una reasignación recurrente de variable.
    

0
1
2
3
4


## **Matrices, modificación de matrices y operaciones**

Un sistema de ecuaciones algebraicas lineales tiene la forma general:

$a_{11}x_{1}+a_{12}x_{2}+...+a_{1n}x_{n}=b_{1}$

$a_{21}x_{1}+a_{22}x_{2}+...+a_{2n}x_{n}=b_{2}$

.

.

.

$a_{n}x_{1}+a_{n2}x_{2}+...+a_{nn}x_{n}=b_{n}$

siendo $a$ coeficientes constantes, $b$ las constantes, $n$ el número de ecuaciones y $x$ las incógnitas.

Sistemáticamente se usa la notación matricial para facilitar su resolución, de la siguiente manera:

$\underline{\underline{A}}=$
$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1n}\\
a_{21} & a_{22} & ... & a_{2n}\\
\vdots & \vdots & ... & \vdots\\
a_{n1} & a_{n2} & ... & a_{nn}
\end{bmatrix}$

donde cada elemento $a_{ij}$ representa un elemento de la matriz (los coeficientes constantes).

 **Nota:** De aquí en adelante se usará la siguiente nomenclatura.
 
 $\underline{\underline{M}}:$ matrices
 
 $\underline{V}:$ vectores filas y vectores columnas
 
 $E:$ constantes y escalares
 
 Las incognitas $x_{j}$ se representan en el vector columna:
 
$\underline{X}=$
$\begin{bmatrix}
x_{1}  \\
x_{2}  \\
\vdots \\
x_{n} 
\end{bmatrix}$

Y las constantes $b_{i}$ con el vector columna:

$\underline{B}=$
$\begin{bmatrix}
b_{1}  \\
b_{2}  \\
\vdots \\
b_{n} 
\end{bmatrix}$

Que en sintésis es:
$\underline{\underline{A}}$  $\underline{X}=\underline{B}$

Por lo tanto, el objetivo es despejar el vector $\underline{X}$


## **Formas de definir matrices**

1. Lista de listas
2. Arreglos en numpy
3. Matrices en sympy

### **1. Lista de listas**

Conceptos previos de listas

In [19]:
h = 0 # Se define una variable cualquiera.


In [20]:
mi_lista = [1, 'flor', 1.5, h]  # lista con cualquier tipo de elemento.


In [21]:
mi_lista


[1, 'flor', 1.5, 0]

In [22]:
mi_lista_2 = [mi_lista, 100, 'flor']  # Una lista con una lista dentro.


In [23]:
mi_lista_2


[[1, 'flor', 1.5, 0], 100, 'flor']

Ahora, definiendo matrices como lista de listas.

In [24]:
matriz = [[5, 1, 2],[7, 3, 7],[4, 7,8]]  # Matriz como lista de listas.


In [25]:
matriz


[[5, 1, 2], [7, 3, 7], [4, 7, 8]]

In [26]:
# Una forma gráfica más cómoda.
A = [
     [5, 1, 2],
     [7, 3, 7],
     [4, 7, 8],
               ]


In [27]:
print(A)


[[5, 1, 2], [7, 3, 7], [4, 7, 8]]


In [28]:
# También se puede usar simplemenhte
A

[[5, 1, 2], [7, 3, 7], [4, 7, 8]]

In [29]:
# Tipo de dato
type(A)


list

In [30]:
# Tamaño de la matriz
m = len(A)    # Número de filas de la matriz, o tamaño de la lista A.


In [31]:
m

3

In [32]:
A[0]

[5, 1, 2]

In [33]:
n = len(A[0]) # Número de columnas de la matriz, o tamaño de la primera lista interna de A.

In [34]:
m

3

In [35]:
print('El número de filas de A es:')
print(m)


El número de filas de A es:
3


In [36]:
print('El número de columnas de A es:')
print(n)


El número de columnas de A es:
3


In [37]:
A


[[5, 1, 2], [7, 3, 7], [4, 7, 8]]

In [38]:
# Llamado de un elemento
a00 = A[0][0]


In [39]:
# Impresión de resultados.
print('El elemento de la fila 1 y la columna 1 es:')
print(a00)


El elemento de la fila 1 y la columna 1 es:
5


In [40]:
# Llamado de un elemento
a22 = A[2][2]
a12 = A[1][2]

# Impresión de resultados.
print('\nEl elemento de la fila 3 y la columna 3 es:')
print(a22)
print('\nEl elemento de la fila 2 y la columna 3 es::')
print(a12)



El elemento de la fila 3 y la columna 3 es:
8

El elemento de la fila 2 y la columna 3 es::
7


In [41]:
A


[[5, 1, 2], [7, 3, 7], [4, 7, 8]]

In [42]:
# Llamado de filas
f0 = A[0] # Se llama la primera fila. En Matlab es con 1, acá es con 0.
f2 = A[2] # Se llama la tercera fila.


In [43]:
f2

[4, 7, 8]

In [44]:
# Impresión de resultados.
print('\nLa primera fila es:')  # El comando \n es usado dejar un espacio.
print(f0)
print('\nLa tercera fila es:')
print(f2)



La primera fila es:
[5, 1, 2]

La tercera fila es:
[4, 7, 8]


In [45]:
# Llamado de columnas
c0 = []
for i in range(len(A)):
    c0 += [A[i][0]]


In [46]:
print('\nLa primera columna es:')
print(c0)


La primera columna es:
[5, 7, 4]


### **2. Arreglo en numpy**

In [47]:
# Mediante el módulo numpy con arrays (arreglos).
# Importar la librería
import numpy as np


In [48]:
# Definición explícita.
B = np.array([
              [3, 1, 9],
              [2, 4, 1],
                       ])


In [49]:
# Impresión de resultados
print('\n La matriz B es:')  
print(B)



 La matriz B es:
[[3 1 9]
 [2 4 1]]


In [50]:
# Definición directa con una variable previamente guardada.
C = [
     [3, 1, 9],
     [2, 4, 1],
              ]

D = np.array(C)


In [51]:
D


array([[3, 1, 9],
       [2, 4, 1]])

In [52]:
# Tipo de dato
type(B)


numpy.ndarray

In [53]:
# Tamaño de la matriz
dim_B = B.shape
print(dim_B)  # Imprime el tamaño del arreglo B.


(2, 3)


In [54]:
# Tipo de dato
type(dim_B)


tuple

In [55]:
# Definiendo número de filas y columnas.
m = dim_B[0]  # Filas
n = dim_B[1]  # Columnas


In [56]:
# Impresión de resultados
print('El número de filas es:')
print(m)
print('El número de columnas es:')
print(n)


El número de filas es:
2
El número de columnas es:
3


In [57]:
A

[[5, 1, 2], [7, 3, 7], [4, 7, 8]]

In [58]:
type(A)

list

In [59]:
A.shape  # Genera error.


AttributeError: 'list' object has no attribute 'shape'

Otras formas de definir arreglos:

In [60]:
# Arreglo de unos
E = np.ones((4, 5))


In [61]:
print(E)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
type(E)

numpy.ndarray

In [63]:
E[0, 0]

1.0

In [64]:
print("\nCon elementos de tipo:")
print(type(E[0][0]))



Con elementos de tipo:
<class 'numpy.float64'>


In [65]:
# Arreglo de ceros
F = np.zeros((3, 2))


In [66]:
F

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
print("\nCon elementos de tipo:")
print(type(F[0][0]))


Con elementos de tipo:
<class 'numpy.float64'>


In [68]:
# Matriz vacía rellena con los valores residuales de la memoria.
G = np.empty((2, 3)) 


In [69]:
print(G)
print("\nCon elementos de tipo:")
print(type(G[0][0]))


[[0. 0. 0.]
 [0. 0. 0.]]

Con elementos de tipo:
<class 'numpy.float64'>


In [70]:
# De forma opcional se puede definir el tipo de dato que tendrá el arreglo.
H = np.zeros((3, 3), dtype=int)  # dytpe tiene muchísimas posibilidades.


In [71]:
H

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [72]:
print("\nCon elementos de tipo:")
print(type(H[0][0]))



Con elementos de tipo:
<class 'numpy.int32'>


In [73]:
# Matriz identidad para matrices cuadradas
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
# Matriz identidad en un caso más general mxn
np.eye(3, 4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [75]:
sp.zeros(3,2)

NameError: name 'sp' is not defined

Llamado de elementos, filas y columnas.

In [76]:
B # Previamente fue definida la matriz B.


array([[3, 1, 9],
       [2, 4, 1]])

In [77]:
# Llamado de un elemento
b12 = B[1][2] # En la numeración natural sería el elemento de la fila 2 y la columna 3.

print(f'El elemento b12 es: {b12}')  # Nótese el uso de la f y de {}.


El elemento b12 es: 1


In [78]:
B[0][0]


3

In [79]:
B[0, 0]

3

In [80]:
# Alternativamente, se usa así:
b12 = B[1, 2]

print(f'El elemento b12 es: {b12}')


El elemento b12 es: 1


In [81]:
B

array([[3, 1, 9],
       [2, 4, 1]])

In [82]:
B[0]


array([3, 1, 9])

In [83]:
# Llamado de una fila
f1 = B[0] # Se llama la PRIMERA fila.

print(f'La segunda fila es: {f1}')


La segunda fila es: [3 1 9]


In [84]:
f2 = B[2] # Se llama la tercera fila. Como no existe: genera error.


IndexError: index 2 is out of bounds for axis 0 with size 2

In [85]:
B[0]

array([3, 1, 9])

In [86]:
B[:, 1]

array([1, 4])

In [87]:
B

array([[3, 1, 9],
       [2, 4, 1]])

In [88]:
# Llamado de columnas
c1 = B[:, 1]
       
print(f'La segunda columna es: {c1}')


La segunda columna es: [1 4]


In [89]:
# Se define una matriz C, nuevamente con
C = np.array([
              [ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15],  # Nótese que esta ',' del final no genera ningún error.
                              ])

print(f'La matriz C es: \n{C}')


La matriz C es: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Llamado de más de una fila o de una columna:

In [90]:
C[1:]


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
C[:2]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
C[:, :2]


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [94]:
C[1:, :2]


array([[ 4,  5],
       [ 8,  9],
       [12, 13]])

In [95]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
C[1:3, 1:3]


array([[ 5,  6],
       [ 9, 10]])

### **3. Matrices en sympy**

In [97]:
# Mediante el módulo sympy con "Array" y con "Matrix".
# Importar la librería
import sympy as sp


In [98]:
J = sp.Array([[ 8,  1,  9],[-1,  4, -2],[ 2, -4,  1],])

In [99]:
J

[[8, 1, 9], [-1, 4, -2], [2, -4, 1]]

In [100]:
# Definición con 'Array', no se recomienda usar pues es inmutable.

J = sp.Array([
              [ 8,  1,  9],
              [-1,  4, -2],
              [ 2, -4,  1],
                          ])


In [101]:
# Impresión de resultados
print('La matriz J es:')  
J  # Acá no se pone el comando 'print' para que genere un 'Out', y en sympy se hace con LaTeX.


La matriz J es:


[[8, 1, 9], [-1, 4, -2], [2, -4, 1]]

In [102]:
print(J)

[[8, 1, 9], [-1, 4, -2], [2, -4, 1]]


In [103]:
print(sp.pretty(J))

⎡8   1   9 ⎤
⎢          ⎥
⎢-1  4   -2⎥
⎢          ⎥
⎣2   -4  1 ⎦


In [104]:
# Tipo de dato
type(J)


sympy.tensor.array.dense_ndim_array.ImmutableDenseNDimArray

In [105]:
# Definición con "Matrix"
K = sp.Matrix([
               [-1,  1,  9],
               [ 4,  4, -2],
               [ 2,  0,  8],
                           ])


In [106]:
# Impresión de resultados
print('La matriz K es:')  
K


La matriz K es:


Matrix([
[-1, 1,  9],
[ 4, 4, -2],
[ 2, 0,  8]])

In [107]:
# Tipo de dato
type(K)


sympy.matrices.dense.MutableDenseMatrix

In [108]:
K.shape

(3, 3)

In [109]:
# Tamaño de la matriz
dim_K = K.shape  # Nótese que es el mismo comando en numpy y en sympy
print(dim_K)     # Imprime el tamaño del arreglo K


(3, 3)


In [110]:
# Tipo de dato
type(dim_K)


tuple

Formas específicas de arreglos:

Se recomienda revisar en detalle la documentación de sympy en: https://docs.sympy.org/latest/tutorial/matrices.html

Las siguientes matrices tienen la forma de 'Matrix', es decir, son mutables:

In [111]:
# Matriz de ceros.
sp.zeros(2)


Matrix([
[0, 0],
[0, 0]])

In [112]:
sp.zeros(3, 2)


Matrix([
[0, 0],
[0, 0],
[0, 0]])

In [113]:
# Matriz de unos.
sp.ones(3)


Matrix([
[1, 1, 1],
[1, 1, 1],
[1, 1, 1]])

In [114]:
# Matriz identidad
sp.eye(3)


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [115]:
# Matriz diagonal
sp.diag(1, 2, 3, 4)


Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0],
[0, 0, 0, 4]])

Llamado de elementos, filas y columnas.

In [116]:
K # Previamente fue definida la matriz K.


Matrix([
[-1, 1,  9],
[ 4, 4, -2],
[ 2, 0,  8]])

In [117]:
# Teniendo en cuenta la longitud de matriz, es decir, la cantidad de elementos.
len(K)  # Nótese que aquí sí se puede usar el comando "len()" a diferencia de numpy.


9

In [118]:
# Se puede llamar a cualquiera de los elementos de la matriz en un ordenamiento que recorre fila por fila.
K[5]


-2

In [119]:
K[1, 1]  # Llamado del último elemento, que es lo mismo que llamar K[8]


4

In [120]:
# Pero el llamado básico se hace de la misma manera que numpy
K[1, 1]  # No funciona poner K[1][1], genera error.


4

In [121]:
K[0, 0]

-1

In [122]:
K

Matrix([
[-1, 1,  9],
[ 4, 4, -2],
[ 2, 0,  8]])

In [123]:
# Llamado de filas
K.row(1)  # LLamado de la segunda fila


Matrix([[4, 4, -2]])

In [124]:
# Alternativamente
K[1, :] # También se puede llamar así, simpre y cuando se use coma intermedia.


Matrix([[4, 4, -2]])

In [125]:
# Llamado de columnas
K.col(2)


Matrix([
[ 9],
[-2],
[ 8]])

In [126]:
# Alternativamente
K[:, 2]

Matrix([
[ 9],
[-2],
[ 8]])

In [127]:
# Se pueden hacer estos llamados de manera similar a numpy
K[1:, 1:]


Matrix([
[4, -2],
[0,  8]])

# **Modificación de elementos**

Cambiar algún elemento de la matriz

### **1. En una lista de listas**

In [128]:
A # Previamente fue definida la matriz A.


[[5, 1, 2], [7, 3, 7], [4, 7, 8]]

In [129]:
# Por ejemplo, el elemento de la fila 3 y la columna 1
A[2][0]


4

In [130]:
# Se puede modificar directamente
A[2][0] = 0


In [131]:
A  # Matriz A modificada


[[5, 1, 2], [7, 3, 7], [0, 7, 8]]

### **2. En un array de numpy**

In [132]:
C # Previamente fue definida la matriz C.


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
C[2, 1]


9

In [134]:
# Modificando el elemento C[2, 1]
C[2, 1] = -15


In [135]:
C  # Matriz C modificada


array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8, -15,  10,  11],
       [ 12,  13,  14,  15]])

In [136]:
# Así modifico toda la fila 2 simultáneamente
C[2]

array([  8, -15,  10,  11])

In [137]:
C[2] = 0

In [138]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15]])

In [139]:
# Por ejemplo, así se modifican todos los elementos.
C[:, :] = 0


In [140]:
C


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### **3. En una matriz de sympy**

In [141]:
K # Previamente fue definida la matriz K.


Matrix([
[-1, 1,  9],
[ 4, 4, -2],
[ 2, 0,  8]])

In [142]:
type(K)

sympy.matrices.dense.MutableDenseMatrix

In [143]:
K[2,2]

8

In [144]:
K[2, 2] = -10

In [145]:
K

Matrix([
[-1, 1,   9],
[ 4, 4,  -2],
[ 2, 0, -10]])

In [146]:
# Modificando el elemento K[1, 1]
K[1, 1] = 0


In [147]:
K  # Matriz K modificada


Matrix([
[-1, 1,   9],
[ 4, 0,  -2],
[ 2, 0, -10]])

In [148]:
K[8]

-10

In [149]:
# Pilas que así se modifica el elemento 2 del recorrido fila a fila.
K[2] = 1


In [150]:
K


Matrix([
[-1, 1,   1],
[ 4, 0,  -2],
[ 2, 0, -10]])

In [151]:
# Si se quiere modificar la columna 1.
K.col(1)


Matrix([
[1],
[0],
[0]])

In [152]:
# Se genera error.
K.col(1) = -100


SyntaxError: cannot assign to function call (<ipython-input-152-56f824f47dfd>, line 2)

In [153]:
# La forma alternativa de llamar la columna 1.
K[:, 1]


Matrix([
[1],
[0],
[0]])

In [154]:
# Si se trata de modificar
K[:,1] = -100


ValueError: unexpected value: -100

In [155]:
# Una forma correcta es:
K[:,1] = (-100, -100, -100)


In [156]:
K


Matrix([
[-1, -100,   1],
[ 4, -100,  -2],
[ 2, -100, -10]])

# **Operaciones con matrices y vectores**
1. Suma
2. Multiplicación
3. Inversión
4. Matriz transpuesta
5. Producto punto y producto cruz

Las operaciones básicas presentan algunas dificultades en una lista de lista, por lo que, claramente es mejor realizar las operaciones con los módulos numpy y sympy.

### **1. Suma**

La suma de matrices solo es posible en matrices del mismo tamaño $mxn$.

La suma de las matrices $\underline{\underline{A}}$ y $\underline{\underline{B}}$ es denotada por: $\underline{\underline{A}}+\underline{\underline{B}}$

**Usando numpy**

In [157]:
# Usando el módulo numpy se crean las matrices M y N.
M = np.array([
              [ 2, 7],
              [-1, 3],
                     ])

N = np.array([
              [-3, 4],
              [ 9, -2],
                     ])


In [158]:
M

array([[ 2,  7],
       [-1,  3]])

In [159]:
N

array([[-3,  4],
       [ 9, -2]])

In [160]:
M+N  # La suma de las matrices M y N.


array([[-1, 11],
       [ 8,  1]])

¿Qué pasa si las matrices a sumar son diferente tamaño?

In [161]:
B  # Llamando la matriz B, previmante definida


array([[3, 1, 9],
       [2, 4, 1]])

In [162]:
B+N  # Lo que ocurre si se suman matrices de diferente tamaño.


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

**Usando sympy**

In [163]:
# Se crean algunas variables simbólicas con sympy.
a, b, c, d = sp.symbols("a b c d")


In [164]:
# Usando el módulo sympy se crean las matrices O y P.
O = sp.Matrix([
               [ a, c],
               [ b, d],
                      ])

P = sp.Matrix([
               [-a, b],
               [ c, d],
                      ])


In [165]:
O

Matrix([
[a, c],
[b, d]])

In [166]:
P

Matrix([
[-a, b],
[ c, d]])

In [167]:
O-P  # La resta de las matrices O y P.


Matrix([
[  2*a, -b + c],
[b - c,      0]])

### **2. Multiplicación**

El producto de una matriz A de tamaño $axb$ con una matriz B de tamaño $cxd$ solo es posible si $b=c$ y, en donde la matriz resultante tendrá un tamaño $axd$.

La multiplicación de las matrices $\underline{\underline{A}}$ y $\underline{\underline{B}}$ es denotada por: $\underline{\underline{A}}$ * $\underline{\underline{B}}$

**Usando numpy**

In [168]:
# Usando el módulo numpy se crean las matrices Q y R.
Q = np.array([
              [3, -2],
                     ])

R = np.array([
              [ 3],
              [-1],
                  ])


In [169]:
Q

array([[ 3, -2]])

In [170]:
R

array([[ 3],
       [-1]])

In [171]:
np.matmul(Q, R)  # La operación Q*R hace otra cosa completamente diferente.


array([[11]])

In [172]:
Q@R  # Otra forma más sencilla de hacer la misma operación.


array([[11]])

In [173]:
Q*R  # No sigue las reglas matriciales, pues debería dar de 1x1

array([[ 9, -6],
       [-3,  2]])

Los arreglos en numpy permiten realizar sobre ellos las operaciones básicas **elemento a elemento**, lo cual no responde a las reglas de las operaciones con matrices.

In [174]:
N

array([[-3,  4],
       [ 9, -2]])

In [175]:
# No sigue reglas matriciales, pero funciona.
N + 100  # Es equivalente a la suma de una matriz de unos multiplicada por el escalar. 


array([[ 97, 104],
       [109,  98]])

In [176]:
N * 3  # Es equivalente a N+N+N, es la multiplicación de una matriz por un escalar.


array([[-9, 12],
       [27, -6]])

In [177]:
N@N # Para multiplicar una matriz por sí misma.


array([[ 45, -20],
       [-45,  40]])

In [178]:
# No sigue las reglas de las operaciones con matrices.
N**2  # Matricialmente no es lo mimso que NxN. Porque lo que hace es elevar a la potencia elemento por elemento.


array([[ 9, 16],
       [81,  4]], dtype=int32)

In [179]:
(N+2)**2/8  # No sigue las reglas de matrices.


array([[ 0.125,  4.5  ],
       [15.125,  0.   ]])

In [180]:
N

array([[-3,  4],
       [ 9, -2]])

In [181]:
1/N  # Cuidado, que esta operacción no es la matriz inversa.



array([[-0.33333333,  0.25      ],
       [ 0.11111111, -0.5       ]])

In [182]:
# ¿Qué ocurre si se eleva a potencias negativas.
N**-1  # Se parece a la inversa, pero NO ES LA INVERSA


ValueError: Integers to negative integer powers are not allowed.

**Usando sympy**

In [183]:
# Usando el módulo sumpy se crea la matriz A y el vector X.

# Se crean algunas variables simbólicas adicionales.
x, y = sp.symbols("x y")

A = sp.Matrix([
               [ a, b],
               [ c, d],
                      ])

X = sp.Matrix([
               [x],
               [y],
                  ])


In [184]:
A


Matrix([
[a, b],
[c, d]])

In [185]:
X


Matrix([
[x],
[y]])

In [186]:
A*X  # En sympy sí se puede hacer esta operación así. operacion matricial


Matrix([
[a*x + b*y],
[c*x + d*y]])

Algunas consideraciones sobre las operaciones:

In [187]:
A  # Llamando la matriz previamente definida.


Matrix([
[a, b],
[c, d]])

In [188]:
# Nótese que aquí sí se respetan las reglas de las operaciones entre matrices.
A+10


TypeError: cannot add <class 'sympy.matrices.dense.MutableDenseMatrix'> and <class 'int'>

In [189]:
# Las matrices se pueden multiplicar por escalares.
O*15


Matrix([
[15*a, 15*c],
[15*b, 15*d]])

In [190]:
# Esta operación sí representa la multiplicación de O con O.
O**2


Matrix([
[a**2 + b*c,  a*c + c*d],
[ a*b + b*d, b*c + d**2]])

### **3. Inversión de matrices**
Solo es posible invertir matrices cuadradas no singulares, es decir, que su determinante sea diferente de 0.

La inversa de la matriz  $\underline{\underline{A}}$ es denotada por $\underline{\underline{A}}^{-1}$.

El determinante de la matriz a se puede denotar como $det(\underline{\underline{A}})$ o como $|\underline{\underline{A}}|$.

**Usando numpy**

In [191]:
# Usando el módulo numpy se crea la matriz S.
S = np.array([[ 1, -2],
              [-3, 5]])


In [192]:
S  # Se imprime S


array([[ 1, -2],
       [-3,  5]])

In [193]:
# Se usa el submódulo np.linalg
np.linalg.det(S)  # Se determina el determinante de la matriz S.


-1.0000000000000004

In [194]:
# Como el determinante es diferente de 0, la matriz es inversible.
np.linalg.inv(S)  # Inversa de la matriz S.


array([[-5., -2.],
       [-3., -1.]])

¿Qué ocurre si se trata de sacar la inversa de una matriz singular?

In [195]:
W = np.array([[ 1, -2],
              [-2,  4]])


In [196]:
np.linalg.det(W)


0.0

In [197]:
np.linalg.inv(W)


LinAlgError: Singular matrix

**Usando sympy**

In [198]:
# Usando la matriz A previamente creada con varibles simbólicas.
A


Matrix([
[a, b],
[c, d]])

In [199]:
# Cálculo del determinante.
A.det()


a*d - b*c

In [200]:
A.inv()  # Inversa de la matriz A. Aquí la utilidad del módulo sympy para determinar fórmulas generales.


Matrix([
[ d/(a*d - b*c), -b/(a*d - b*c)],
[-c/(a*d - b*c),  a/(a*d - b*c)]])

In [201]:
A**-1  # Esta operación sí es la inversa de la matriz, al contrario de lo que ocurre en numpy.


Matrix([
[ d/(a*d - b*c), -b/(a*d - b*c)],
[-c/(a*d - b*c),  a/(a*d - b*c)]])

### **4. Matriz transpuesta**
Se denota a la transpuesta de la matriz $\underline{\underline{A}}$ como $\underline{\underline{A}}^{T}$.

¿Cómo se transpone la matriz $\underline{\underline{A}}$? (ejercicio de clase con lista de listas)

In [202]:
A = [[  0,  1,  2,  3,  4],
     [  5,  6,  7,  8,  9],
     [ 10, 11, 12, 13, 14]]


In [203]:
len(A)

3

In [204]:
len(A[0])

5

In [205]:
# Solución
#for i in range(len(A))

# Espacio de memoria para una matriz 5X3
m = len(A)
n = len(A[0])

AT = []
for i in range(n):  # 0, 1, 2, 3, 4
    AT += [[]]
    for j in range(m): # 0, 1, 2
        AT[i] += [0]
        

In [206]:
AT

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [207]:
# Creamos la matriz transpuesta
for i in range(n):
    for j in range(m):
        AT[i][j] = A[j][i]


In [208]:
A


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [209]:
AT


[[0, 5, 10], [1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14]]

**Usando numpy**

In [210]:
B # Previamente fue definida la matriz B.


array([[3, 1, 9],
       [2, 4, 1]])

In [211]:
B.T  # Matriz transpuesta.


array([[3, 2],
       [1, 4],
       [9, 1]])

**Usando sympy**

In [212]:
K # Previamente fue definida la matriz K.


Matrix([
[-1, -100,   1],
[ 4, -100,  -2],
[ 2, -100, -10]])

In [213]:
K.T  # Matriz transpuesta.


Matrix([
[  -1,    4,    2],
[-100, -100, -100],
[   1,   -2,  -10]])

### **5. Producto punto y producto cruz**

El producto punto o producto escalar de dos vectores está definido como:

$\underline{A}.\underline{B}=(a_1, a_2, ..., a_n).(b_1, b_2, ..., b_n)=a_1b_1+a_2b_2+...+a_nb_n=\sum a_i b_i$

Alternativamente, se puede definir como:

$\underline{A}.\underline{B}=||\underline{A}||.||\underline{B}||cos(\theta)$, donde $\theta$ es el ángulo formado entre los vectores.

**Nota:**
De aquí en adelante un vector entre dos líneas a lado y lado representará la magnitud o norma: $||\underline{A}||$.

Una matriz entre dos líneas representa un determinante: $|\underline{\underline{A}}|$.

**Pregunta de clase**

¿Qué significa que el $\underline{A}.\underline{B}=0$?


La razon es que los vectores son perperdiculares.


**Pregunta de clase**

¿Qué significa que el $\underline{A}.\underline{B}=||\underline{A}||.||\underline{B}||$?

Significa que ángulo es cero, o, son **paralelos**.

El producto cruz o producto vectorial de dos vectores está definido en $\mathbb R^{3}$ como $\underline{A}$x$\underline{B}$, en donde:

$\underline{A}=(a_x, a_y, a_z)$\
$\underline{B}=(b_x, b_y, b_z)$

es decir,

$\underline{A}$ x $\underline{B}$ $= \left|
\begin{array}{ccc}
\hat{i} & \hat{j} & \hat{k}\\
a_x & a_y & a_z\\
b_x & b_y & b_z\\
\end{array}
\right|
$

In [214]:
# Este código por el momento no es necesario estudiarlo.
# Usando sympy se obtiene 
import sympy as sp
ax, ay, az, bx, by, bz = sp.symbols("a_x a_y a_z b_x b_y b_z")
ig, jg, kg = sp.symbols("\hat{i} \hat{j} \hat{k}")

AxB = sp.Matrix([
                 [ig, jg, kg],
                 [ax, ay, az],
                 [bx, by, bz]
                             ]).det()

sp.collect(AxB, [ig, jg, kg])  # Factorizar de acuerdo a unas expresiones


\hat{i}*(a_y*b_z - a_z*b_y) + \hat{j}*(-a_x*b_z + a_z*b_x) + \hat{k}*(a_x*b_y - a_y*b_x)

De esta manera, $\underline{A}$ x $\underline{B}=\underline{C}$, donde:

$\underline{C}=(c_x, c_y, c_z)$,

$c_x=a_y.b_z - a_z.b_y$\
$c_y=-a_x.b_z + a_z.b_x$\
$c_z=a_x.b_y - a_y.b_x$

Además, es últil la definición:

$||\underline{A}$ x $\underline{B}||$ = $||\underline{A}||$  $||\underline{B}||$  $|sin(\theta)|$


**Pregunta de clase**

¿Qué significa que $\underline{A}$ x $\underline{B}$ = $\underline{0}$

Son paralelos

**Usando numpy**

In [215]:
# Se crean los vectores u1 y u2.
u1 = np.array([7, -4, -1])
u2 = np.array([3, -5,  2])


In [216]:
u1  # Se visualiza el vector u1.


array([ 7, -4, -1])

In [217]:
u2  # Se visualiza el vector u2.


array([ 3, -5,  2])

In [218]:
# El producto punto de u1 y u2.
np.dot(u1, u2)


39

**Usando sympy**

In [219]:
# Se crean algunas variables simbólicas
a1, a2, a3, b1, b2, b3 = sp.symbols("a_1 a_2 a_3 b_1 b_2 b_3")


In [220]:
# Se crean los vectores v1 y v2 con las variables simbólicas disponibles.
v1 = sp.Matrix([a1, a2, a3])
v2 = sp.Matrix([b1, b2, b3])

In [221]:
v1  # Se visualiza el vector v1.


Matrix([
[a_1],
[a_2],
[a_3]])

In [222]:
v2  # Se visualiza el vector v2.


Matrix([
[b_1],
[b_2],
[b_3]])

In [223]:
# El producto punto de v1 y v2.
v1.dot(v2)  # Es lo mismo que v2.dot(v1) 


a_1*b_1 + a_2*b_2 + a_3*b_3

In [224]:
# El producto cruz de v1 y v2.
v3 = v1.cross(v2)  # Es diferente a v2.cross(v1)

v3  # Se imprime v3.


Matrix([
[ a_2*b_3 - a_3*b_2],
[-a_1*b_3 + a_3*b_1],
[ a_1*b_2 - a_2*b_1]])

AxB = -BxA

In [225]:
# El producto punto de v1 y v3.
v1.dot(v3)  # Debería dar 0.


a_1*(a_2*b_3 - a_3*b_2) + a_2*(-a_1*b_3 + a_3*b_1) + a_3*(a_1*b_2 - a_2*b_1)

In [226]:
sp.simplify(v1.dot(v3))  # Se usa el comando "simplify".


0

In [227]:
# El producto punto de v2 y v3.
sp.simplify(v2.dot(v3))


0

**Resumen de conocimientos**
- Lo más básico de Python
- Formas de definir matrices
- Modificación de elementos
- Operaciones con matrices y vectores


**Resumen de comandos usados**
- +
- -
- *
- /
- //
- %
- **
- +=
- ==
- !=
- print()
- type()
- len()
- for \_\_ in \_\_ :
- np.array()
- \_\_.shape
- np.ones()
- np.zeros()
- np.empty()
- dtype
- np.identitity()
- np.eye()
- sp.Array()
- sp.Matrix()
- sp.zeros()
- sp.ones()
- sp.eye()
- sp.diag()
- \_\_, \_\_ = sp.symbols('\_\_ \_\_')
- np.linalg.det()
- np.linalg.inv()
- \_\_.det()
- \_\_.inv()
- \_\_.T
- sp.collect()
- sp.simplify()
- np.dot(\_\_, \_\_)
- \_\_.dot(\_\_)
- \_\_.cross(\_\_ )