**4101553 Métodos Numéricos aplicados a la Ingenieria Civil**
-

Departamento de Ingeniería Civil

Universidad Nacional de Colombia

Sede Manizales

**Docente:** Juan Nicolás Ramírez Giraldo ([jnramirezg@unal.edu.co](mailto:jnramirezg@unal.edu.co))


"*Cum cogitaveris quot te antecedant, respice quot sequantur*" **Séneca**

[Repositorio de la asignatura](https://github.com/jnramirezg/metodos_numericos_ingenieria_civil/)

---

**Unidad 1: Sistemas de ecuaciones lineales**
-
# **1.6. Soluciones de sistemas en Python**

---
Se presentan los comandos y funciones más importantes que se relacionan con solución de sistemas de ecuaciones lineales y álgebra lineal. Para ello, se usan las librerías `numpy` y `sympy`, además, de una nueva librería con alto uso en ámbitos científicos: `scipy`.

---

Se importan las librerías:

In [1]:
import numpy as np
import sympy as sp


---

## **1.6.1. En `numpy`**
- `np.linalg.solve(a, b)`
- `np.linalg.cholesky(a)`
- `np.linalg.norm(v)`
- `np.linalg.eig(a)` y `np.linalg.eigvals(a)`

En ocasiones, y por facilidad, se le suele hacer un llamado al submódulo `linalg` de `numpy` así:

In [2]:
from numpy import linalg as LA


---

### `LA.solve(a, b)`


Ejemplo 1:

In [3]:
A1 = [[-1, -1,  6,  9],
      [-5,  5, -3,  6],
      [ 7, -3,  5, -6],
      [ 3, -3, -2,  3]]

B1 = [-29, -54, 38, 41]


In [4]:
LA.solve(A1, B1)


array([ 4., -8., -4., -1.])

Se anota que los argumentos de la función pueden ser pasados como lista de listas y lista, o también como `np.array`.

---

Ejemplo 2: sistema singular no detectado

In [5]:
A2 = [[ 2,  1,  4, -1],
      [ 3, -2,  1,  0],
      [ 5,  1, -3,  2],
      [-1,  3,  3, -1]]

B2 =  [1, -1, 4, 3]


In [6]:
LA.solve(A2, B2)


array([ 7.70352568e+14,  3.55547339e+14, -1.59996303e+15, -4.50359963e+15])

Debido a que se trata de un resultado muy sospechoso, se verifica el valor del determinante:

In [7]:
LA.det(A2)


-1.6875389974302392e-14

Claramente `A2` es una matriz singular que, genera un sistema singular, sin embargo, la función no lo detectó por la representación numérica. Por lo tanto, es pertinente poner la advertencia en un programa donde se use la función `LA.solve()`.

---

Ejemplo 3:

In [8]:
A3 = [[ 1, -1,  1],
      [-2,  2, -2], 
      [ 2,  4,  2]]

B3 = [1, 2, 1]


In [9]:
LA.solve(A3, B3)


LinAlgError: Singular matrix

Se verifica el valor del determinante:

In [10]:
LA.det(A3)


0.0

La causa del error es `LinAlgError: Singular matrix`, lo cual es completamente coherente con el resultado del determinante.

---

Ejemplo 4: valores muy cercanos a cero en la diagonal.

In [11]:
A4 = [[0.00000000000000000000000003, 3.0000],
      [1.0000,                       1.0000]]
B4 = [ 2.00000000000000000000000001, 1.0000] 


In [12]:
LA.solve(A4, B4)


array([0.33333333, 0.66666667])

No se evidencia ningún incoveniente como sí ocurría en otros métodos.

---

Ejemplo 5:

In [13]:
A5 = [[-9,  7,  2,  5,  7],
      [ 5,  3, -2,  2, -6],
      [ 2, -6, -5, -7, -8],
      [-2,  4, -2, -2, -6]]

B5 = [1, -1, 4, 3]


In [14]:
LA.solve(A5, B5)


LinAlgError: Last 2 dimensions of the array must be square

En este caso la fuente de error es `LinAlgError: Last 2 dimensions of the array must be square`, es decir, la matriz no es cuadrada.

---

Ejemplo 6:

In [15]:
A6 = [[-1,  2],
      [ 3, -1]]

B6 = [[1, 4, 10],
      [2, 1,  3]]


In [16]:
LA.solve(A6, B6)


array([[1. , 1.2, 3.2],
       [1. , 2.6, 6.6]])

De hecho, tiene mucho sentido pues sigue la siguiente estructura algebraica:

$
\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}
\begin{bmatrix}
x_{11} & x_{12} & x_{13}  \\
x_{21} & x_{22} & x_{23} 
\end{bmatrix}
=\begin{bmatrix}
b_{11} & b_{12} & b_{13}  \\
b_{21} & b_{22} & b_{23} 
\end{bmatrix}$

En donde se tiene 3 sistemas de ecuaciones de $2x2$, pero cuyos coeficientes constantes son iguales, cambiando únicamente sus constantes. De hecho, hubiéramos podido programar nuestros métodos previos de esta manera.

Es equivalente a resolver:

$
\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}
\begin{bmatrix}
x_{11}\\
x_{21} 
\end{bmatrix}
=\begin{bmatrix}
b_{11}\\
b_{21} 
\end{bmatrix}$

$
\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}
\begin{bmatrix}
x_{12}\\
x_{22} 
\end{bmatrix}
=\begin{bmatrix}
b_{12}\\
b_{22} 
\end{bmatrix}$

$
\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}
\begin{bmatrix}
x_{13}\\
x_{23} 
\end{bmatrix}
=\begin{bmatrix}
b_{13}\\
b_{23} 
\end{bmatrix}$

---

### `LA.cholesky(a)`

Ejemplo 1: matriz definida positiva y simétrica

In [17]:
A1 = np.array([[ 6,  3,  4,  8], 
               [ 3,  6,  5,  1], 
               [ 4,  5, 10,  7],
               [ 8,  1,  7, 25]])


In [18]:
LA.cholesky(A1)


array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])

In [19]:
L = LA.cholesky(A1)


In [20]:
L@L.T


array([[ 6.,  3.,  4.,  8.],
       [ 3.,  6.,  5.,  1.],
       [ 4.,  5., 10.,  7.],
       [ 8.,  1.,  7., 25.]])

---

Ejemplo 2: cuando no se cumple que la matriz esté definida positiva y sea simétrica.

In [21]:
A2 = [[-1, -1,  6,  9],
      [-5,  5, -3,  6],
      [ 7, -3,  5, -6],
      [ 3, -3, -2,  3]]


In [22]:
LA.cholesky(A2)


LinAlgError: Matrix is not positive definite

---

### `LA.norm(v)`

La norma de un vector en $\mathbb{R}^n$

$\underline{V}=(v_0, v_1, v_2,....v_n)$ es:

$||\underline{V}||=\sqrt{v_0^2+v_1^2+v_2^2,...,v_n^2}$



In [23]:
V = [-1, 2, -2]


In [24]:
LA.norm(V)


3.0

---

### `LA.eig(a)` y `LA.eigvals(a)`

Los valores de $\lambda$ se obtienen de la solución del polinomio característico que surge de: $|\underline{\underline{A}}-\lambda\underline{\underline{I}}|=0$.

Y los vectores propios son aquellos que satisfacen para cada valor de $\lambda$ la ecuación $(\underline{\underline{A}}-\lambda\underline{\underline{I}})\underline{X}=\underline{0}$.

Por cada $\lambda$ hay un vector propio.

In [25]:
A = [[1, 2],
     [3, 2]]


In [26]:
LA.eigvals(A)


array([-1.,  4.])

---

In [27]:
LA.eig(A)


(array([-1.,  4.]),
 array([[-0.70710678, -0.5547002 ],
        [ 0.70710678, -0.83205029]]))

In [28]:
e, w = LA.eig(A)


La primera parte del resultados es equivalente a usar la función `LA.eig(A)`.

In [29]:
e


array([-1.,  4.])

En la segunda parte del resultado, el primer vector propio es la primera columna y el segundo vector propio es la segunda columna (los vectores ya están normalizados a 1).

In [30]:
w


array([[-0.70710678, -0.5547002 ],
       [ 0.70710678, -0.83205029]])

---

In [31]:
w1 = w[:, 0]
w2 = w[:, 1]


In [32]:
w1


array([-0.70710678,  0.70710678])

In [33]:
LA.norm(w1)


0.9999999999999999

In [34]:
w2


array([-0.5547002 , -0.83205029])

In [35]:
LA.norm(w2)


1.0

---

## **1.6.2. En `sympy`**
- `A.is_positive_definite`
- `A.cholesky()`
- `A.LUdecomposition()`
- `A.LUsolve(B)`
- `V.norm()`
- `A.eigenvals()` y `A.eigenvects()`
- `sp.solve(ecu, X)`

---

### `A.is_positive_definite`

In [36]:
A = sp.Matrix([[25, 15, -5], 
               [15, 18,  0], 
               [-5,  0, 11]])


In [37]:
A


Matrix([
[25, 15, -5],
[15, 18,  0],
[-5,  0, 11]])

Y por si parece extraño, mire esta otra forma de definir la misma matriz. Dependiendo de la aplicación que se desarrolle, puede ser útil una u otra.

In [38]:
# Los dos primeros argumentos indican el tamaño.
sp.Matrix(3, 3, (25, 15, -5, 15, 18,  0, -5,  0, 11))


Matrix([
[25, 15, -5],
[15, 18,  0],
[-5,  0, 11]])

In [39]:
A.is_positive_definite


True

---

### `A.cholesky()`

In [40]:
A.cholesky()


Matrix([
[ 5, 0, 0],
[ 3, 3, 0],
[-1, 1, 3]])

In [41]:
L = A.cholesky()


In [42]:
L*L.T - A


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

---

### `A.LUdecomposition()`

In [43]:
A = sp.Matrix([[4, 3], 
               [6, 3]])


In [44]:
A.LUdecomposition()


(Matrix([
 [  1, 0],
 [3/2, 1]]),
 Matrix([
 [4,    3],
 [0, -3/2]]),
 [])

In [45]:
L, U, _ = A.LUdecomposition()


In [46]:
L


Matrix([
[  1, 0],
[3/2, 1]])

In [47]:
U


Matrix([
[4,    3],
[0, -3/2]])

In [48]:
L*U - A


Matrix([
[0, 0],
[0, 0]])

---

### `A.LUsolve(B)`

Ejemplo 1:

In [49]:
A = sp.Matrix([[-1, -1,  6,  9],
               [-5,  5, -3,  6],
               [ 7, -3,  5, -6],
               [ 3, -3, -2,  3]])

B = sp.Matrix([-29, -54, 38, 41])


In [50]:
A.LUsolve(B)


Matrix([
[ 4],
[-8],
[-4],
[-1]])

---

Ejemplo 2:

In [51]:
A = sp.Matrix([[-1,  2],
               [ 3, -1]])

B = sp.Matrix([[1, 4, 10],
               [2, 1,  3]])


In [52]:
A.LUsolve(B)


Matrix([
[1,  6/5, 16/5],
[1, 13/5, 33/5]])

---

### `V.norm()`

In [53]:
V = sp.Matrix([-1, 2, -2])


In [54]:
V.norm()


3

---

### `A.eigenvals()` y `A.eigenvects()`

In [55]:
A = sp.Matrix([[1, 2],
               [3, 2]])


In [56]:
A.eigenvals()  # Sus valores propios son 4 y -1


{4: 1, -1: 1}

In [57]:
A.eigenvects()


[(-1,
  1,
  [Matrix([
   [-1],
   [ 1]])]),
 (4,
  1,
  [Matrix([
   [2/3],
   [  1]])])]

---

In [58]:
A.eigenvects()[0][2][0]  # Vector propio 1.


Matrix([
[-1],
[ 1]])

In [59]:
A.eigenvects()[1][2][0] # Vector propio 2.


Matrix([
[2/3],
[  1]])

---

### `sp.solve(ecu, X)`

Se definen las variables simbólicas de las incógnitas para un sistema $3x3$.

In [60]:
x0, x1, x2 = sp.symbols('x_0, x_1, x_2')


Ejemplo 1:

Se define `ecu`: ecuaciones e `inc`: incógnitas.

In [61]:
ecu = [5*x0 - 2*x1 + 1*x2 - 24,
       2*x0 + 5*x1 - 2*x2 + 14,
       1*x0 - 4*x1 + 3*x2 - 26]

inc = [x0, x1, x2]


In [62]:
sp.solve(ecu, inc)


{x_0: 3, x_1: -2, x_2: 5}

---

Ejemplo 2:

In [63]:
A = sp.Matrix([[5, -2, 1],
               [2, 5, -2],
               [1, -4, 3]])

B = sp.Matrix([[24],
               [-14],
               [26]])

X = sp.Matrix([[x0],
               [x1],
               [x2]])


In [64]:
sp.solve(A*X-B, X)


{x_0: 3, x_1: -2, x_2: 5}

Se le puede indicar qué método usar con el argumento opcional `method`. Por ejemplo, cuando se tienen matrices simétricas definidas positivas se puede poner `method='CH'`.

In [65]:
sp.solve(A*X-B, X, method='LU')


{x_0: 3, x_1: -2, x_2: 5}

---

In [66]:
X = sp.solve(A*X-B, X)


In [67]:
X[x0]


3

In [68]:
X[x1]


-2

In [69]:
X[x2]


5

---

Ejemplo 3: un sistema $3x3$ muy simbólico.

In [70]:
a0, a1, a2 = sp.symbols('a_0 a_1 a_2')
a3, a4, a5 = sp.symbols('a_3 a_4 a_5')
a6, a7, a8 = sp.symbols('a_6 a_7 a_8')

b0, b1, b2 = sp.symbols('b_0 b_1 b_2')


In [71]:
A = sp.Matrix([[a0, a1, a2],
               [a3, a4, a5],
               [a6, a7, a8]])

B = sp.Matrix([[b0],
               [b1],
               [b2]])

X = sp.Matrix([[x0],
               [x1],
               [x2]])


In [72]:
sol = sp.solve(A*X - B, X)


---

In [73]:
sol[x0]


(a_1*a_5*b_2 - a_1*a_8*b_1 - a_2*a_4*b_2 + a_2*a_7*b_1 + a_4*a_8*b_0 - a_5*a_7*b_0)/(a_0*a_4*a_8 - a_0*a_5*a_7 - a_1*a_3*a_8 + a_1*a_5*a_6 + a_2*a_3*a_7 - a_2*a_4*a_6)

In [74]:
sol[x1]


(-a_0*a_5*b_2 + a_0*a_8*b_1 + a_2*a_3*b_2 - a_2*a_6*b_1 - a_3*a_8*b_0 + a_5*a_6*b_0)/(a_0*a_4*a_8 - a_0*a_5*a_7 - a_1*a_3*a_8 + a_1*a_5*a_6 + a_2*a_3*a_7 - a_2*a_4*a_6)

In [75]:
sol[x2]


(a_0*a_4*b_2 - a_0*a_7*b_1 - a_1*a_3*b_2 + a_1*a_6*b_1 + a_3*a_7*b_0 - a_4*a_6*b_0)/(a_0*a_4*a_8 - a_0*a_5*a_7 - a_1*a_3*a_8 + a_1*a_5*a_6 + a_2*a_3*a_7 - a_2*a_4*a_6)

---

## **1.6.3. En `scipy`**

- scipy.linalg.solve(a, b)
- scipy.linalg.lu(a)

In [76]:
from scipy.linalg import lu, solve


---

In [77]:
A = [[-1, -1,  6,  9],
     [-5,  5, -3,  6],
     [ 7, -3,  5, -6],
     [ 3, -3, -2,  3]]

B = [-29, -54, 38, 41]


In [78]:
lu(A)


(array([[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-0.71428571,  1.        ,  0.        ,  0.        ],
        [-0.14285714, -0.5       ,  1.        ,  0.        ],
        [ 0.42857143, -0.6       , -0.54285714,  1.        ]]),
 array([[ 7.        , -3.        ,  5.        , -6.        ],
        [ 0.        ,  2.85714286,  0.57142857,  1.71428571],
        [ 0.        ,  0.        ,  7.        ,  9.        ],
        [ 0.        ,  0.        ,  0.        , 11.48571429]]))

---

In [79]:
solve(A, B)


array([ 4., -8., -4., -1.])

Revisemos qué tipos de dato se arrojan:

In [80]:
type(lu(A)[0])


numpy.ndarray

In [81]:
type(solve(A, B))


numpy.ndarray

**Comandos adicionales para el tratamiento de expresiones en `Sympy`:**

- sp.collect()
- sp.simplify()
- sp.expand()
